<a href="https://colab.research.google.com/github/viiditjain/elevatelabs-task-4/blob/main/task4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder, StandardScaler

In [3]:
# Load Adult Income dataset
df = pd.read_csv("/content/drive/MyDrive/adult.csv")
df.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

In [4]:
df.shape

(48842, 15)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              48842 non-null  int64
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64
 11  capital-loss     48842 non-null  int64
 12  hours-per-week   48842 non-null  int64
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB

In [6]:
categorical_features = df.select_dtypes(include=['object']).columns
numerical_features = df.select_dtypes(include=['int64', 'float64']).columns

categorical_features, numerical_features

(Index(['workclass', 'education', 'marital-status', 'occupation',
        'relationship', 'race', 'gender', 'native-country', 'income'],
       dtype='object'),
 Index(['age', 'fnlwgt', 'educational-num', 'capital-gain', 'capital-loss',
        'hours-per-week'],
       dtype='object'))

In [7]:
# Replace '?' with NaN
df.replace('?', np.nan, inplace=True)

# Fill missing categorical values with mode
for col in categorical_features:
    df[col].fillna(df[col].mode()[0], inplace=True)

/tmp/ipython-input-2974196454.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

In [8]:
label_encoder = LabelEncoder()
df['income'] = label_encoder.fit_transform(df['income'])

In [9]:
df_encoded = pd.get_dummies(
    df,
    columns=[col for col in categorical_features if col != 'income'],
    drop_first=True
)

In [10]:
scaler = StandardScaler()

df_encoded[numerical_features] = scaler.fit_transform(
    df_encoded[numerical_features]
)

In [11]:
df_encoded.head()

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week,income,workclass_Local-gov,workclass_Never-worked,workclass_Private,...,native-country_Portugal,native-country_Puerto-Rico,native-country_Scotland,native-country_South,native-country_Taiwan,native-country_Thailand,native-country_Trinadad&Tobago,native-country_United-States,native-country_Vietnam,native-country_Yugoslavia
0,-0.995129,0.351675,-1.197259,-0.144804,-0.217127,-0.034087,0,False,False,True,...,False,False,False,False,False,False,False,True,False,False
1,-0.046942,-0.945524,-0.419335,-0.144804,-0.217127,0.772930,0,False,False,True,...,False,False,False,False,False,False,False,True,False,False
2,-0.776316,1.394723,0.747550,-0.144804,-0.217127,-0.034087,1,True,False,False,...,False,False,False,False,False,False,False,True,False,False
3,0.390683,-0.277844,-0.030373,0.886874,-0.217127,-0.034087,1,False,False,True,...,False,False,False,False,False,False,False,True,False,False
4,-1.505691,-0.815954,-0.030373,-0.144804,-0.217127,-0.841104,0,False,False,True,...,False,False,False,False,False,False,False,True,False,False

In [12]:
df_encoded.shape

(48842, 98)

In [13]:
df_encoded.to_csv("adult_income_preprocessed.csv", index=False)